micronaut:
    application:
        name: api-java
    server:
        port: 8086
        cors:
            enabled: true
            configurations:
                all:
                    exposedHeaders:
                        - Content-Type
                        - Authorization
                        - Content-Range

    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        interceptUrlMap:
            -
                pattern: /hello/*
                httpMethod: GET
                access:
                    - isAnonymous()
            -
                pattern: /tasks
                access:
                    - isAuthenticated()
            -
                pattern: /tasks/*
                access:
                    - isAuthenticated()
#      -
#        pattern: /books/grails
#        httpMethod: GET
#        access:
#          - ROLE_ADMIN
#          - ROLE_MANAGER
#          - ROLE_STAFF
        token:
            jwt:
                enabled: true
                signatures:
                    secret:
                    generator:
                        secret: pleaseChangeThisSecretForANewOne
                        base64: true
                        jws-algorithm: HS256

jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

datasources:
    default:
        url: jdbc:h2:mem:default;INIT=RUNSCRIPT FROM 'classpath:db/migration/V1__init_task_table.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
jpa:
    default:
        packages-to-scan:
            - 'sample.domain'
        properties:
            hibernate:
                hbm2ddl:
#                    auto: update
                    auto: none
                show_sql: true


