micronaut:
    application:
        name: api-java
    server:
        port: 8086
        cors:
            enabled: true
            configurations:
                web:
#                    allowedHeaders:
#                        - Content-Type
#                        - Authorization
                    exposedHeaders:
                        - Content-Type
                        - Authorization
                        - Content-Range
jackson:
    dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

datasources:
    default:
        url: jdbc:h2:mem:default;INIT=RUNSCRIPT FROM 'classpath:db/migration/V1__init_task_table.sql';DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
jpa:
    default:
        packages-to-scan:
            - 'sample.domain'
        properties:
            hibernate:
                hbm2ddl:
#                    auto: update
                    auto: none
                show_sql: true